version: '3.8'
services:
  dev-db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: school
    ports:
      - "5432:5432"
  test-db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: school
    ports:
      - "5435:5432"